#!/bin/bash

#=====================================================
# File setup
#=====================================================
DIR="$HOME/.config/songd"
HEADERS="$DIR/headers.csv"
DATA="$DIR/db.csv"

# Exit if headers file not found
[ -s "$HEADERS" ] || { (>&2 echo Currupted Data...); (>&2 echo Please reinstall); exit 3; }
# Exit if no data found
[ -s "$DATA" ] || { echo Nothing found to delete; echo Use songd-add or songd menu to add more songs and then try deleting them \;\); exit 0; }

#=====================================================
# User used cli..Nice!
#=====================================================
if (( $# > 0 )); then

    if (( $# % 2 != 0 )); then
        (>&2 echo Please pass in the correct number of arguments and values)
        (>&2 echo Aborting)
        exit 1;
    fi

    while (( $# > 0 )); do
        arg="$1"

        case $arg in
            -i|--index )
                index="$2"
                shift; shift ;;
            * )
                (>&2 echo Error in parsing "$1")
                (>&2 echo Aborting)
                exit 1 ;;
        esac
    done

    # Check if the index provided is actually a number
    re='^[0-9]+$'
    [[ $index =~ $re ]] || { (>&2 echo Please provide a valid index); exit 1; }

    # Check if the index provided exceeds the max value
    if (( $index > $( wc -l "$DATA" | cut -d' ' -f1 ) )); then
        (>&2 echo The index you provided exceeds the maximum index)
        (>&2 echo Please provide a valid index)
        exit 1
    fi

else
#=====================================================
# User used interactive method
#=====================================================
    # Load the menu function
    . ./menu.sh

    heading="Please choose the song you want to delete"

    # convert spaces to comma hack for menu display
    options=( $( cat "$DATA" | cut -d, -f2 | tr -s ' ' | tr ' ' ',' ) )

    heading "$heading"
    menu "${options[@]}"

    index=$?
    index=$(( $index+1 ))
fi

#=====================================================
# Actually delete the entry
#=====================================================
COLUMNS=( $( cat "$HEADERS" | sed 's/,\(.\)/,\U\1/g' | cut -d, -f2- ) )
row=( "$( sed -n $index'p' "$DATA" | cut -d, -f2- )" )

echo
printf "%s\n%s\n" "${COLUMNS[@]}" "${row[@]}" | column -s, -t
echo
read -p 'Are you sure you want to delete this song? [y/N]:' del

case $del in
    y*|Y* )
        sed -i "$index d" "$DATA"
        echo Song was succesfully deleted
        ;;
    n*|N*|''|* )
        echo Song was not deleted
        ;;
esac

